name: checkstyle
on:
  pull_request:
    branches: [ "master" ]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          reporter: github-pr-review
          level: warning