version: "3.9" #version of docker-compose
services:
  db:
    container_name: mysql
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=tms
      - MYSQL_ROOT_PASSWORD=root
#  tomcat:
#    image: "tomcat:9.0.58-jdk17-openjdk-slim"
#    container_name: "tomcat"
#    environment:
#      JPDA_ADDRESS: "*:8000"
#      JPDA_TRANSPORT: "dt_socket"
#    volumes:
#      - "./target/lesson27-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/servlet.war"
#    ports:
#      - "8080:8080"
#    entrypoint: "/usr/local/tomcat/bin/catalina.sh jpda run"
#    depends_on:
#      - "db"