name: spotbugs

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B verify com.github.spotbugs:spotbugs-maven-plugin:4.7.1.1:spotbugs
      - uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: 'codequality/spotbugs.xml'
